artifact_uri: file:C:/Users/syami/OneDrive/Desktop/springboard_creditpath_Ai/mlflow_runs/176050669943814112/18bd29040ac14a0bbedcb451cdd4b3b1/artifacts
end_time: 1775117378380
entry_point_name: ''
experiment_id: '176050669943814112'
lifecycle_stage: active
run_id: 18bd29040ac14a0bbedcb451cdd4b3b1
run_name: XGBoost
source_name: ''
source_type: 4
source_version: ''
start_time: 1775117356024
status: 3
tags: []
user_id: syami
