artifact_uri: file:C:/Users/syami/OneDrive/Desktop/springboard_creditpath_Ai/mlflow_runs/176050669943814112/8c8e5c37cd834cf8b05f87ff2cf92a9f/artifacts
end_time: 1775117117162
entry_point_name: ''
experiment_id: '176050669943814112'
lifecycle_stage: active
run_id: 8c8e5c37cd834cf8b05f87ff2cf92a9f
run_name: XGBoost
source_name: ''
source_type: 4
source_version: ''
start_time: 1775117083226
status: 3
tags: []
user_id: syami
