artifact_location: file:C:/Users/syami/OneDrive/Desktop/springboard_creditpath_Ai/mlflow_runs/176050669943814112
creation_time: 1775115870274
experiment_id: '176050669943814112'
last_update_time: 1775115870274
lifecycle_stage: active
name: loan_default_prediction
workspace: default
